### ISSUE TITLE
Planned deprecation for product curl commands?

### ISSUE THREAD

**Issue by cdurante** [tadpol/MrMurano#55]
When using the -L switch for product commands, it's clear that the interactions with Murano - Product components are done via OnePlatform RPC API. 

Is there a planned deprecation of this interaction model for Murano projects in favor of something new in the future? 

We are currently using some of the MrMurano-derived curl commands in MFG process to enable and provision new devices, and would like to get an idea of future refactoring effort required for these processes.

**Comment by tadpol** [comment]
Using the OnePlatform RPC API with Murano is deprecated. The replacement API is still in deep development, which is why the product interactions are using 1P RPC APIs still.

The future of these things would be better answered by others. @dweaver

**Comment by dweaver** [comment]
@tadpol's response is spot on. MrMurano uses some unpublished device management APIs, and we're planning a rolling update for those starting in roughly a month. That's going to affect you if you reverse engineered MrMurano using `-L` and now rely on those API endpoints directly.

I recommend using MrMurano directly since it will be updated to use the new APIs, and it's easier to upgrade MrMurano than to change API calls. We do intend to document the new APIs as soon as we can after the rolling upgrades so that you can use the new APIs directly. 

Note that these API upgrades don't affect any of Murano's documented APIs, e.g. device-facing ones.

**Comment by cdurante** [comment]
Thanks for the info!
